---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zjh.
--- DateTime: 2025/10/28 18:27
---
-- 1.ARGV参数列表
-- 优惠券id
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]

-- 2.redis存储数据的key前缀
-- 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单key
local orderKey = 'seckill:order' .. voucherId

-- 3.脚本业务(符合资格返回0，不符合返回非0：1代表库存不足，2代表已下过单)
-- 3.1 判断库存，不足则返回1, 注意redis返回的是字符串，这里要转成数字再进行判断
if (redis.call('get', stockKey) <= 0) then
    return 1
end
-- 3.2 判断一人一单，不满足则返回2
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
-- 3.3 扣减库存
redis.call('incrby', stockKey, -1)
-- 3.4 下单（保存用户）
redis.call('sadd', orderKey, userId)
-- 3.5 发送订单信息到消息队列
redis.call('xadd', 'streams.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

-- 3.6 符合资格，返回0
return 0
