---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zjh.
--- DateTime: 2025/10/28 13:36
---

-- KEYS[1]是锁的key，ARGV[1]是线程标识
-- 获取当前锁的标识，判断是否与线程标识一致

if (redis.call('GET', KEYS[1]) == ARGV[1]) then
    -- 一致，删除锁
    return redis.call('DEL', KEYS[1])
end
-- 不一致，直接返回
return 0
